rss:
  channel:
    atom-link:
      href: https://api.mseiche.de/rss/feed
    image:
      url: https://strapi.mseiche.de/uploads/favicon_primary_21e9ac0793.png
      link: https://mseiche.de
      width: 48
      height: 48
      title: MSeiche Logo
      description: Manuel Seiche's Website Logo
    title: Manuel Seiche's Blog
    description: On this page I am posting about some implementation stuff. Because I'm much more of a developer than an author, you'll often see code samples or even interactive UI components for demonstration purposes.
    link: https://mseiche.de/blog
strapi:
  model: post
  collection-url: https://strapi.mseiche.de/posts
item-factory:
  guid: https://mseiche.de/blog/posts/<</id>>
  link: https://mseiche.de/blog/posts/<</id>>
  title: <</title>>
  description: <</description>>
  pub-date: <</created_at>>